name: event_loop_watchdog
description: A Dart package to help detect whenever your main `event loop` is blocked.
version: 0.1.0
repository: https://github.com/KDAB/event_loop_watchdog.git

environment:
  sdk: ^3.0.0

dependencies:
  vm_service:
  path:

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
